### ISSUE TITLE
[Feature Request] One button to auto do All or Favourited missions

### ISSUE THREAD

**Issue by solkarnar** [zealvurte/SimSimMissionWin#6]
Hi there, first off, just wanna say a big thank you for picking up the mantle to continue where Venture Plan has left off.

With that being said, I think there has been a frequent request (amongst my friends and guild at least) for Venture Plan to have a button to auto assign / simulate and do multiple missions. So I reckon I would post it here because the best time for development requests is early in the development cycle.

For eg. I would like to do all gold missions and anima missions while skipping certain ones like experience or enchanting mats ones. Not sure if doing All missions is feasible given the complexity in calculating all combinations, but perhaps certain favourited categories could be automated.

Once again, thank you and good luck with the new addon. Really looking forward to it. Cheers.

**Comment by zealvurte** [comment]
Thanks for the support. Unfortunately, as with VP, this isn't feasible for the Shadowlands system.

The closest I will be getting to such a feature is having it save your (and perhaps in future, crowd-sourced) most successful compositions and allowing you to simply send one of those if available, but this is on a per mission basis (i.e. you will need to figure out which compositions allow you to do all the missions you want), so wouldn't work well for bulk missions (there's simply too many variables to calculate that each time, and if relying on stored data instead it would be too excessive to store so many possible successful composition).
