### ISSUE TITLE
logs for verification

### ISSUE THREAD

**Issue by LostTemple1990** [zealvurte/SimSimMissionWin#9]
[logs.txt](https://github.com/zealvurte/SimSimMissionWin/files/7164717/logs.txt)
I've added a table you listed in #2 to collect these logs

By the way,
It seems that the **spell 9** works well in sim using the key `healPercent` ,
which you said it should be `healPerc` in [this issue](https://github.com/hythloday/VenturePlanSoDMissions/issues/17)
I've checked the source code in vs.lua.
Surprisingly,it uses `healPercent` in heal(**spell 9**) but `healPerc` in aura(**spell 10**).
Perhaps you have modified them to a same key before the last valid version because it's so strange to use two different keys to implement the same function

**Comment by zealvurte** [comment]
> Surprisingly,it uses `healPercent` in heal(**spell 9**) but `healPerc` in aura(**spell 10**)
> Perhaps you have modified them to a same key before the last valid version because it's so strange to use two different keys to implement the same function

Huh, you're right, I must have changed it at some point and didn't mark the change. 😣

`mu:heal` is the only place that used `healPercent`, while `mu:aura` and `mu:dtick` used `healPerc`, so spell 9 didn't need changing (I've removed that from the comment now). I'll need to modify [SimData-Spells_tsv-to-lua.lua](../blob/main/SimData-Spells_tsv-to-lua.lua) to properly handle this for the unmodified VP output.

Thanks for spotting that. I'll look at the logs tomorrow.

**Comment by zealvurte** [comment]
Logs cover:
Missions (#2)
```lua
{
	[2170]=true,	-- Rot-Heart's Final Rest
	[2172]=true,	-- Wolfram Alpha
	[2176]=true,	-- Erezuel and His Pack
	[2194]=true,	-- Campaign: Erezuel's Rampage
	[2200]=true,	-- Pride Before the Fall
	[2211]=true,	-- Campaign: Whisper in the Dark
	[2217]=true,	-- Fall and Fall Again
	[2218]=true,	-- Bonewrought? Bone-wrong, Belike
	[2234]=true,	-- Rampaging Bonemaulers
	[2286]=true,	-- Overgrown Abominations
	[2290]=true,	-- Vyrm the Ravenous
	[2296]=true,	-- Maw: Breach the Planes
	[2297]=true,	-- Maw: Ghelak's Revenge
}
```
All verified, thanks again!
